import type { Manifest } from '../registry/manifest.js';
import { AGENT_GUIDE } from './agentGuide.js';
import { GROUP_NOTES } from './groupNotes.js';

const HEADER = '<!-- GENERATED by npm run gen:docs — do not edit by hand -->\n\n';

/** Content of packages/cli/AGENTS.md. */
export function renderAgentsMd(): string {
  return HEADER + AGENT_GUIDE;
}

/** Content of packages/cli/COMMANDS.md — the human command reference. */
export function renderCommandsMd(manifest: Manifest): string {
  const lines: string[] = [
    HEADER + '# kelta CLI — Command Reference',
    '',
    `CLI version ${manifest.cliVersion} · manifest v${String(manifest.manifestVersion)} · ` +
      `output formats: ${manifest.outputFormats.join(', ')}`,
    '',
    'Global flags on every command: `--profile`, `--output`, `--raw`, `--quiet`, `--yes`.',
    'Full machine-readable catalog: `kelta manifest`.',
    '',
  ];

  const groups = new Map<string, typeof manifest.commands>();
  for (const command of manifest.commands) {
    const key = command.group || '(top level)';
    const list = groups.get(key) ?? [];
    list.push(command);
    groups.set(key, list);
  }

  for (const [group, commands] of groups) {
    lines.push(`## ${group}`, '');
    const note = GROUP_NOTES[group];
    if (note) {
      lines.push(note, '');
    }
    for (const command of commands) {
      const positionals = command.positionals
        .map((positional) =>
          positional.required ? `<${positional.name}>` : `[${positional.name}]`
        )
        .join(' ');
      const title = [command.command, positionals].filter(Boolean).join(' ');
      lines.push(
        `### \`${title}\``,
        '',
        command.summary + (command.dangerous ? ' **(destructive — needs --yes off-TTY)**' : ''),
        ''
      );
      if (command.options.length > 0) {
        for (const option of command.options) {
          const suffix = [
            option.default !== undefined ? `default: ${JSON.stringify(option.default)}` : '',
            option.repeatable ? 'repeatable' : '',
          ]
            .filter(Boolean)
            .join(', ');
          lines.push(`- \`${option.flag}\` — ${option.description}${suffix ? ` (${suffix})` : ''}`);
        }
        lines.push('');
      }
    }
  }
  return lines.join('\n');
}
