import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';
import { SECTION_IDS } from './docs/sidebar';

// Hand-written documentation pages. Directory == section by convention (not
// enforced): src/content/docs/<section>/<page>.md → /docs/<section>/<page>/.
const docs = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/docs' }),
  schema: z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    section: z.enum(SECTION_IDS),
    order: z.number().int().nonnegative(),
    tocDepth: z.union([z.literal(2), z.literal(3)]).default(3),
    status: z.enum(['partial']).optional(),
    draft: z.boolean().default(false),
  }),
});

// Canonical authoring docs. They live at the repo root and are tri-published
// (the CLI embeds them, the MCP server serves them as kelta://docs/<topic>), so
// the site reads them in place rather than keeping a copy. No frontmatter by
// design — titles and sidebar placement come from src/docs/externalMeta.ts.
const authoring = defineCollection({
  loader: glob({ pattern: '*.md', base: '../docs/authoring' }),
  schema: z.object({}).strict(),
});

// Generated by `npm run gen:docs` in kelta-web; rendered at /docs/cli/{commands,agents}/.
const cli = defineCollection({
  loader: glob({ pattern: ['COMMANDS.md', 'AGENTS.md'], base: '../kelta-web/packages/cli' }),
  schema: z.object({}).strict(),
});

export const collections = { docs, authoring, cli };
